### PR TITLE
Added stealth check to scan function (in ship model)

### PR DESCRIPTION
**Pull request by CaitlinBerger**
Scan will no longer return true for ships with the stealth attribute. 
Changed stealth variable to Boolean instead of int. 
Added test for stealth check in ship model scan function.

### CODE REVIEW

**Comment by RiverHendriksen** [comment]
There is a merge conflict, also this won't pass the tests that are currently there

**Comment by RiverHendriksen** [comment]
I think the conflicts are due to to the pull that just happened that removes cruiser and destroyer

**Comment by CaitlinBerger** [comment]
Okay, I fixed the merge conflicts

**Comment by RiverHendriksen** [comment]
looks good thanks for changing the tests

**Pull request merged**
