### PR TITLE
Removed all references to destroyer and cruiser, replaced with dinghy…

### PR DESCRIPTION
**Pull request by gbauer9**
… and clipper

### CODE REVIEW

**Comment by CaitlinBerger** [comment]
Looks good. Great work!

**Comment by RiverHendriksen** [comment]
You need to change the test cases, one of them (i believe main.test) has a long string

**Comment by RiverHendriksen** [comment]
You shouldn't have merged this code wont work with the test suite

**Comment by CaitlinBerger** [comment]
Oops sorry! I figured he could update tests in a separate commit/pull request.

**Comment by CaitlinBerger** [comment]
Do you want me to revert?

**Comment by RiverHendriksen** [comment]
as long as he knows to fix it I think it's cool? it's just more of an issue of that we now have broken code in our master

**Pull request merged**
