### PR TITLE
added civilian ships to model

### PR DESCRIPTION
**Pull request by anish-94**

### CODE REVIEW

**Comment by RiverHendriksen** [comment]
hey dude we need to comment we accept a merge. I was looking it over when you merged it

**Comment by gbauer9** [comment]
My bad I was just going to comment afterwards.

**Comment by gbauer9** [comment]
Good work Anish. I ran the program and everything looked fine. One thing that we need to remember to do is update the html and js so that the user can select the new civilian ships.

**Comment by anish-94** [comment]
I was thinking about that. Do the civilian ships need to be placed by the user or are they just there at a random position? 

Also, can they be detected by scanning? The way I have it right now, they cannot be detected via scan.

**Comment by RiverHendriksen** [comment]
I think we should let the player decide? Also I added the stealth feature to the civilian ships and they can be scanned currently

**Pull request merged**
