### PR TITLE
added stealth and tests for stealth

### PR DESCRIPTION
**Pull request by RiverHendriksen**
I added the stealth feature to all ships and created a test in battleship model to ensure that the stealth value works. Some of the previous tests did not compile due to both the stealth addition and that dinghy and clipper were added. Those issues are now fixed as well. 

We are currently sitting at 100% code coverage and 92% line coverage.

### CODE REVIEW

**Comment by anish-94** [comment]
I was just looking at that. If you look at the scan function, there is a return true/false. Can we just modify that instead of adding another variable? 

I think we get the same outcome but it's just code that is already there. I could be missing something though. I will be able to test the code in a little while.

**Comment by RiverHendriksen** [comment]
The scan function has a variable currently but it is not associated with stealth only if it finds a ship. I am not working on the scan function, I believe it was Caitlin is doing that. The plan was to have a stealth variable on the ships.java and the scan function will test to see whether that is true of false. The code being merged has the stealth boolean and fixes test issues that are present in the current code on the master.

**Comment by anish-94** [comment]
What I mean is this function which was there in the model file: 

    `
public void scan(int rowInt, int colInt) {

        Coordinate coor = new Coordinate(rowInt,colInt);

        scanResult = false;

        if(computer_aircraftCarrier.scan(coor)){

            scanResult = true;
 
       }

        else if (computer_battleship.scan(coor)){

            scanResult = false;

        }else if (computer_cruiser.scan(coor)){

            scanResult = true;

        }else if (computer_destroyer.scan(coor)){

            scanResult = true;

        }else if (computer_submarine.scan(coor)){

            scanResult = false;

        }else if(computer_dinghy.scan(coor)){

            scanResult = false;

        }else if(computer_clipper.scan(coor)){

            scanResult = false;

        }else {

            scanResult = false;

        }

    }
`

**Comment by RiverHendriksen** [comment]
i guess i don't know what you mean?

**Pull request merged**
